#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PACKAGE=encodings
PKG_VER=1.1.0
URL=https://www.x.org/pub/individual/font/$PACKAGE-$PKG_VER.tar.xz
TAR=$PACKAGE-$PKG_VER.tar.xz
DIR=$PACKAGE-$PKG_VER

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --sysconfdir=/etc --disable-static


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


