#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PACKAGE=font-util
PKG_VER=1.4.1
URL=https://www.x.org/pub/individual/font/font-util-$PKG_VER.tar.xz
TAR=$PACKAGE-$PKG_VER.tar.xz
DIR=$PACKAGE-$PKG_VER

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr --sysconfdir=/etc --disable-static


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


