#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.15.0
URL=https://github.com/containers/aardvark-dns/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=aardvark-dns-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export RUSTUP_TOOLCHAIN=stable
export CARGO_TARGET_DIR=target



cargo build --release --all-features --frozen



# Install
mkdir -p /pkgs/$PACKAGE/usr/bin
install -vDm755 target/release/$PACKAGE  -t /pkgs/$PACKAGE/usr/lib/podman
cd /pkgs



sudo echo "libgcc" > /pkgs/$PACKAGE/depends
sudo echo "rustc" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
# Method 2 install
cp -rpv /pkgs/$PACKAGE /
cd /blfs/builds
sudo rm -r $DIR


