#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=1.2.14
URL=https://www.alsa-project.org/files/pub/utils/alsa-utils-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -e 's/acp-pdm-dmic/acp-dmic-codec/'                   \
    -e '/LABEL="alsa_restore_go"/s/go/std/'               \
    -e '/^ENV.ALSA_CARD_NUMBER/i LABEL="alsa_restore_go"' \
    -i alsactl/90-alsa-restore.rules.in

./configure --disable-alsaconf \
            --with-curses=ncursesw


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "fftw" > /pkgs/$PACKAGE/depends
sudo echo "xmlto python-docutils" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


