#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1.2.8
URL=https://www.alsa-project.org/files/pub/lib/alsa-ucm-conf-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



# Install
mkdir -p /pkgs/$PACKAGE/usr/share/alsa/
cp -av ucm2 /pkgs/$PACKAGE/usr/share/alsa/
install -vDm 644 README.md -t /pkgs/$PACKAGE/usr/share/doc/$PACKAGE/
install -vDm 644 README.md -t /pkgs/$PACKAGE/usr/share/doc/$PACKAGE/ucm2
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
sudo cp -rpv /pkgs/$PACKAGE/* /

cd /blfs/builds
sudo rm -r $DIR


