#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=1.2.5.1
URL=https://www.alsa-project.org/files/pub/lib/alsa-topology-conf-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



# Install
# credit to arch linux build-scripts
for dir in topology/*; do
    install -vDm 644 "$dir"/*.conf -t "/pkgs/$PACKAGE/usr/share/alsa/topology/$(basename $dir)"
done

cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
sudo cp -rpv /pkgs/$PACKAGE/* /


cd /blfs/builds
sudo rm -r $DIR


