#!/bin/bash
#NLFS
export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=35.0.2
URL=https://github.com/nmeum/android-tools/releases/download/$PKG_VER/android-tools-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
cmake -Dprotobuf_MODULE_COMPATIBLE=ON  -DCMAKE_INSTALL_PREFIX=/usr -DANDROID_TOOLS_LIBUSB_ENABLE_UDEV=ON  -DANDROID_TOOLS_USE_BUNDLED_LIBUSB=ON -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON  -DCMAKE_BUILD_TYPE=Release  -G Ninja ..


ninja


# Install
sudo ninja install 
sudo DESTDIR=/pkgs/$PACKAGE ninja install 
cd /pkgs



sudo echo "protobuf fmt zlib libusb ncurses googletest" > /pkgs/$PACKAGE/depends
sudo echo "protobuf" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


