#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=3.10.0
URL=https://github.com/catchorg/Catch2/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=Catch2-$PKG_VER
PACKAGE=catch2

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCATCH_BUILD_EXAMPLES=OFF \
      -DCATCH_ENABLE_COVERAGE=OFF \
      -DCATCH_ENABLE_WERROR=OFF \
      -DBUILD_TESTING=ON \
      -DCATCH_DEVELOPMENT_BUILD=ON \
      -DBUILD_SHARED_LIBS=ON \
      -Wno-dev -G Ninja ..


ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "python" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


