#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2.10.3
URL=https://github.com/cracklib/cracklib/releases/download/v$PKG_VER/cracklib-$PKG_VER.tar.xz
URL2=https://github.com/cracklib/cracklib/releases/download/v$PKG_VER/cracklib-words-$PKG_VER.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


CPPFLAGS+=' -I /usr/include/python3.13' \
./configure --prefix=/usr               \
            --disable-static            \
            --with-default-dict=/usr/lib/cracklib/pw_dict

make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
xzcat ../cracklib-words-$PKG_VER.xz > /pkgs/$PACKAGE/usr/share/dict/cracklib-words
ln -v -sf cracklib-words /pkgs/$PACKAGE/usr/share/dict/words

install -v -m755 -d /pkgs/$PACKAGE/usr/lib/cracklib

create-cracklib-dict /pkgs/$PACKAGE/usr/share/dict/cracklib-words /pkgs/$PACKAGE/usr/share/dict/cracklib-extra-words
cd /pkgs



sudo echo "zlib" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


