#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=4.1.1
URL=http://github.com/checkpoint-restore/criu/archive/v$PKG_VER/criu-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=criu-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

# shellcheck disable=SC2001 -- archlinux
export CFLAGS=$(echo "$CFLAGS" | sed 's/-Wp,-D_FORTIFY_SOURCE=[0-9]//g')
make V=1 criu crit lib amdgpu_plugin docs
python3 -m build --wheel --no-isolation --skip-dependency-check crit
python3 -m build --wheel --no-isolation --skip-dependency-check lib




# Install
sed -e "s,--upgrade --ignore-installed,--no-index --no-deps -v --no-build-isolation,g" -i lib/Makefile -i crit/Makefile
make V=1 \
  DESTDIR=/pkgs/$PACKAGE \
  PREFIX=/usr \
  SBINDIR=/usr/bin \
  LIBDIR=/usr/lib \
  LIBEXECDIR=/usr/lib \
  PIPFLAGS="--no-build-isolation --no-index --no-deps --progress-bar off --upgrade --ignore-installed" \
  install-criu install-lib install-amdgpu_plugin install-cuda_plugin install-crit install-man
# suppress warning
rm -rf "/pkgs/$PACKAGE/usr/include/compel/common/asm"

cd /pkgs



sudo echo "python-protobuf libbsd libgcc gnutls libbpf libdrm libnet libnl nftables protobuf python util-linux" > /pkgs/$PACKAGE/depends
sudo echo "asciidoc git python-build python-installer setuptools wheel xmlto" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


