#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.16.0
URL=https://github.com/flatpak/flatpak/releases/download/$PKG_VER/flatpak-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir -p build
cd build
meson setup --prefix=/usr --buildtype=release ..

ninja

# Install
sudo DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "gnupg glib libsoup libxml2 dconf systemd libarchive gpgme fuse2 ostree json-glib appstream-glib ostree libseccomp libxslt docbook-xml docbook-xsl gtk-doc dconf p11-kit avahi xdg-desktop-portal malcontent" > /pkgs/$PACKAGE/depends
sudo echo "pyparsing socat docbook-xml5" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


