#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=3.0.2
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gimp.org/pub/gimp/v$MAJOR/gimp-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR 
cd $DIR

# Build

# gimp doesn't like other gimp installations? credit: LFS
rm -rf /usr/{lib,share}/gimp/3.0 &&
rm -f  /usr/share/gir-1.0/Gimp-3.0.gir &&
rm -f  /usr/lib/girepository-1.0/Gimp-3.0.typelib &&
rm -f  /usr/lib/libgimp*-3.0.so*

mkdir gbuild
cd gbuild
meson setup ..                   \
      --prefix=/usr              \
      --buildtype=release        \
      -D headless-tests=disabled
ninja

# Install
sudo DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "appstream-glib gegl gexiv2 glib-networking gtk3 harfbuzz libmypaint librsvg libtiff libxml2 lcms mypaint-brushes poppler graphviz ghostscript iso-codes libgudev pygobject3 xdg-utils gjs libjxl" > /pkgs/$PACKAGE/depends
sudo echo "appstream-glib gegl gexiv2 glib-networking gtk3 harfbuzz libmypaint librsvg libtiff libxml2 lcms mypaint-brushes poppler graphviz ghostscript iso-codes libgudev pygobject3 xdg-utils gjs libjxl" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


