#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2.0.7
URL=https://github.com/cpuguy83/go-md2man/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=go-md2man-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

export GOFLAGS="-buildmode=pie -trimpath"

go build -o go-md2man
./go-md2man -in=go-md2man.1.md -out=go-md2man.1



# Install
install -Dm755 go-md2man /pkgs/$PACKAGE/usr/bin/go-md2man
install -Dm755 go-md2man.1 /pkgs/$PACKAGE/usr/share/man/man1/go-md2man.1
cd /pkgs



sudo echo "libgcc" > /pkgs/$PACKAGE/depends
sudo echo "go" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


