#!/bin/bash

export CFLAGS="-O2"
export CXXFLAGS="-O2"

PKG_VER=1.28.2
URL=https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson  setup --prefix=/usr       \
       --buildtype=release \
       -Dpackage-name="GStreamer $PKG_VER For Tucana" &&


ninja


# Install
DESTDIR=/pkgs/$PACKAGE ninja install
ninja install
cd /pkgs


sudo echo "ffmpeg gst-plugins-base" > /pkgs/$PACKAGE/depends
sudo echo "yasm" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR

