#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

URL=https://download.gnome.org/sources/gtk+/2.24/gtk+-2.24.33.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gtk2

# Get Package

cd /blfs/builds
wget $URL
wget https://gitlab.archlinux.org/archlinux/packaging/packages/gtk2/-/raw/main/0002-Stop-looking-for-modules-in-cwd.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../0002-Stop-looking-for-modules-in-cwd.patch

sed -i '/AM_INIT_AUTOMAKE/s/]/ foreign]/' configure.ac
autoreconf -fvi

./configure --prefix=/usr --sysconfdir=/etc --disable-gtk-doc --with-xinput=yes

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "atk gdk-pixbuf pango hicolor-icons" > /pkgs/$PACKAGE/depends
sudo echo "gtk-query-immodules-2.0 --update-cache" > /pkgs/$PACKAGE/postinst
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


