#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
# Last Validated Version 102.4

PKG_VER=115.23.0esr
REFORMAT=$(echo $PKG_VER | sed 's/esr//g')
URL=https://archive.mozilla.org/pub/firefox/releases/${PKG_VER}/source/firefox-${PKG_VER}.source.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=firefox-$REFORMAT
PACKAGE=js115

# Get Package

cd /blfs/builds
wget https://raw.githubusercontent.com/Tucana-Linux/tucana-pkgs-extra/refs/heads/main/js115/js115-build-fix.patch
wget $URL
tar -xvf $TAR
cd $DIR


# Build
patch -Np1 < ../js115-build-fix.patch

mkdir obj &&
cd    obj &&

PYTHON=python3.11

../js/src/configure --prefix=/usr            \
                    --with-intl-api          \
                    --with-system-zlib       \
                    --disable-jemalloc       \
                    --disable-debug-symbols  \
                    --enable-readline    


make -j20


# Install

make DESTDIR=/pkgs/$PACKAGE install
rm /pkgs/$PACKAGE/usr/lib/*.ajs
sed -i '/@NSPR_CFLAGS@/d' /pkgs/$PACKAGE/usr/bin/js115-config
sudo echo "libgcc readline bash zlib icu" > /pkgs/$PACKAGE/depends
sudo echo "python3.11 libgcc readline bash zlib clang llvm python rustc zip git" > /pkgs/$PACKAGE/make-depends
cd /pkgs/$PACKAGE
sudo rm -rf root blfs
cd ..
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
sudo cp -rpv /pkgs/$PACKAGE/* /


cd /blfs/builds
sudo rm -r $DIR


