#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e

PKG_VER=140.3.0esr
REFORMAT=$(echo $PKG_VER | sed 's/esr//g')
URL=https://archive.mozilla.org/pub/firefox/releases/${PKG_VER}/source/firefox-${PKG_VER}.source.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=firefox-$REFORMAT
PACKAGE=js140

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir obj &&
cd    obj &&

../js/src/configure --prefix=/usr            \
                    --with-intl-api          \
                    --with-system-zlib       \
                    --with-system-icu        \
                    --disable-jemalloc       \
                    --disable-debug-symbols  \
                    --enable-readline    


make -j20


# Install

make DESTDIR=/pkgs/$PACKAGE install
rm /pkgs/$PACKAGE/usr/lib/*.ajs
sed -i '/@NSPR_CFLAGS@/d' /pkgs/$PACKAGE/usr/bin/js140-config
sudo echo "libgcc readline bash zlib icu" > /pkgs/$PACKAGE/depends
sudo echo "cbindgen libgcc readline bash zlib clang llvm python rustc zip git" > /pkgs/$PACKAGE/make-depends
sed '$i#define XP_UNIX' -i /pkgs/$PACKAGE/usr/include/mozjs-140/js-config.h
cd /pkgs/$PACKAGE
sudo rm -rf root blfs
cd ..
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
sudo cp -rpv /pkgs/$PACKAGE/* /


cd /blfs/builds
sudo rm -r $DIR


