#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
#ARCH_PKG=libaio
#ARCH_VAR=pkgver
PKG_VER=0.3.113
URL=https://pagure.io/libaio/archive/libaio-$PKG_VER/libaio-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build




make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


