#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=1.5.0
URL=https://github.com/libbpf/libbpf/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=libbpf-$PKG_VER
PACKAGE=libbpf

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build




make -C src -j22


# Install
sudo make -C src DESTDIR=/pkgs/$PACKAGE LIBSUBDIR=lib install install_headers
sudo make install
cd /pkgs



sudo echo "linux-api-headers libelf zlib glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


