#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=249
URL=https://github.com/cjlin1/liblinear/archive/v$PKG_VER/liblinear-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build




make lib


# Install
install -Dvm644 linear.h /pkgs/$PACKAGE/usr/include &&
install -Dvm755 liblinear.so.6 /pkgs/$PACKAGE/usr/lib &&
ln -sfv liblinear.so.6 /usr/lib/liblinear.so
cd /pkgs



sudo echo "glibc" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


