#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=1.3
URL=https://github.com/libnet/libnet/releases/download/v$PKG_VER/libnet-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://src.fedoraproject.org/rpms/libnet/raw/rawhide/f/libnet-config.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../libnet-config.patch
echo "$PKG_VER" > VERSION
autoreconf -vfi
./configure --prefix=/usr


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "glibc bash" > /pkgs/$PACKAGE/depends
sudo echo "doxygen graphviz" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


