#!/bin/bash

export CFLAGS="-O2"
export CXXFLAGS="-O2"

set -e
PKG_VER=21.1.8
URL=https://github.com/llvm/llvm-project/releases/download/llvmorg-$PKG_VER/llvm-$PKG_VER.src.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')

PACKAGE=llvm
PACKAGE2=clang
PACKAGE3=compiler-rt

# Get Package
cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build LLVM Base
grep -rl '#!.*python' | xargs sed -i '1s/python$/python3/'
sed 's/utility/tool/' -i utils/FileCheck/CMakeLists.txt
mkdir build
cd build


CC=gcc CXX=g++                                  \
cmake -DCMAKE_INSTALL_PREFIX=/usr               \
      -DLLVM_ENABLE_FFI=ON                      \
      -DCMAKE_BUILD_TYPE=Release                \
      -DLLVM_BUILD_LLVM_DYLIB=ON                \
      -DLLVM_LINK_LLVM_DYLIB=ON                 \
      -DLLVM_ENABLE_RTTI=ON                     \
      -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
      -DLLVM_BINUTILS_INCDIR=/usr/include       \
      -DLLVM_INCLUDE_BENCHMARKS=OFF             \
      -Wno-dev -G Ninja ..         



ninja


# Install LLVM Base
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs


# Just 1 make depend line, just needs to picked up by autobuild
sudo echo "glibc" > /pkgs/$PACKAGE/depends
echo "cmake" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds/$DIR

# Build Clang
cd clang
grep -rl '#!.*python' | xargs sed -i '1s/python$/python3/'


mkdir build
cd build


CC=gcc CXX=g++                                  \
cmake -DCMAKE_INSTALL_PREFIX=/usr               \
      -DLLVM_ENABLE_FFI=ON                      \
      -DLLVM_INCLUDE_TESTS=OFF                  \
      -DCMAKE_BUILD_TYPE=Release                \
      -DLLVM_BUILD_LLVM_DYLIB=ON                \
      -DLLVM_ENABLE_RTTI=ON                     \
      -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
      -DCLANG_DEFAULT_PIE_ON_LINUX=ON           \
      -Wno-dev -G Ninja ..



ninja


# Install Clang
sudo  DESTDIR=/pkgs/$PACKAGE2 ninja install
sudo ninja install
cd /pkgs



sudo echo "glibc gcc llvm" > /pkgs/$PACKAGE2/depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE2/version
sudo tar -cvapf $PACKAGE2.tar.xz $PACKAGE2
sudo cp $PACKAGE2.tar.xz /finished


cd /blfs/builds/$DIR
# Build Compiler-RT
cd $DIR
cd compiler-rt
grep -rl '#!.*python' | xargs sed -i '1s/python$/python3/'
mkdir build
cd build


CC=gcc CXX=g++                                  \
cmake -DCMAKE_INSTALL_PREFIX=/usr               \
      -DLLVM_ENABLE_FFI=ON                      \
      -DLLVM_INCLUDE_TESTS=OFF                  \
      -DCMAKE_BUILD_TYPE=Release                \
      -DLLVM_BUILD_LLVM_DYLIB=ON                \
      -DLLVM_LINK_LLVM_DYLIB=ON                 \
      -DLLVM_ENABLE_RTTI=ON                     \
      -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
      -DLLVM_BINUTILS_INCDIR=/usr/include       \
      -DLLVM_INCLUDE_BENCHMARKS=OFF             \
      -DCLANG_DEFAULT_PIE_ON_LINUX=ON           \
      -Wno-dev -G Ninja ..         



ninja


# Install Compiler-RT
sudo  DESTDIR=/pkgs/$PACKAGE3 ninja install
sudo ninja install
cd /pkgs



sudo echo "libgcc" > /pkgs/$PACKAGE3/depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE3/version
sudo tar -cvapf $PACKAGE3.tar.xz $PACKAGE3
sudo cp $PACKAGE3.tar.xz /finished


cd /blfs/builds
sudo rm -r $COMPILER_RT_DIR
sudo rm -r $LLVM_DIR
# Cleanup cmake modules
sudo rm -r cmake
