#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=20250528
URL=https://github.com/LuaJIT/LuaJIT.git
DIR=LuaJIT
PACKAGE=luajit

# Get Package

cd /blfs/builds
git clone $URL
cd $DIR

# Build

make PREFIX=/usr amalg



# Install
sudo make PREFIX=/usr DESTDIR=/pkgs/$PACKAGE install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
rm -rf $DIR


