#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=3.20
URL=https://gnu.mirror.constant.com/mailutils/mailutils-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://raw.githubusercontent.com/Tucana-Linux/pkgs-extra-files/refs/heads/main/mailutils/0001-mailutils-gcc-15-fix.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../0001-mailutils-gcc-15-fix.patch
./configure --prefix=/usr --with-gnutls --disable-python


make 


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "gnutls cyrus-sasl pam openldap-client" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


