#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=20091016
URL=http://miniupnp.free.fr/files/miniupnpc-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
make -j22
python setup.py build

# Install
# Fix header file missing stddef.h
sudo make DESTDIR=/pkgs/$PACKAGE install
sed -i '/miniupnpctypes.h/ a #include <stddef.h>' /pkgs/$PACKAGE/usr/include/miniupnpc/upnpcommands.h
install -Dm 644 man3/miniupnpc.3 -t /pkgs/$PACKAGE/usr/share/man/man3
python setup.py install --optimize=1 --skip-build --root=/pkgs/$PACKAGE

cd /pkgs



sudo echo "glibc python" > /pkgs/$PACKAGE/depends
sudo echo "setuptools" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


