#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=6.1.0
URL=https://github.com/moonlight-stream/moonlight-qt/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=moonlight-qt-$PKG_VER
PACKAGE=moonlight

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
qmake6 PREFIX="/pkgs/$PACKAGE/usr" moonlight-qt.pro
make release -j22

# Install
sudo  make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "ffmpeg qt6 sdl2_ttf" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


