#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=1.25.6
URL=https://www.mupdf.com/downloads/archive/mupdf-$PKG_VER-source.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=mupdf-$PKG_VER-source
PACKAGE=mupdf

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



cat > user.make << EOF &&
USE_SYSTEM_FREETYPE := yes
USE_SYSTEM_HARFBUZZ := yes
USE_SYSTEM_JBIG2DEC := no
USE_SYSTEM_JPEGXR := no # not used without HAVE_JPEGXR
USE_SYSTEM_LCMS2 := no # need lcms2-art fork
USE_SYSTEM_LIBJPEG := yes
USE_SYSTEM_MUJS := no # build needs source anyway
USE_SYSTEM_OPENJPEG := yes
USE_SYSTEM_ZLIB := yes
USE_SYSTEM_GLUT := no # need freeglut2-art fork
USE_SYSTEM_CURL := yes
USE_SYSTEM_GUMBO := no
EOF
export XCFLAGS=-fPIC                               &&
make build=release shared=yes -j22                      &&
unset XCFLAGS





# Install

make prefix=/pkgs/$PACKAGE/usr                        \
     shared=yes                         \
     install                            &&

chmod 755 /pkgs/$PACKAGE/usr/lib/libmupdf.so          &&
ln -sfv mupdf-x11 /pkgs/$PACKAGE/usr/bin/mupdf
cd /pkgs


cp -rpv /pkgs/$PACKAGE/* /
sudo echo "lcms glu xorg-libs harfbuzz libjpeg-turbo openjpeg curl" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


