#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

#ARCH_VAR=pkgver
#ARCH_PKG=nano
PKG_VER=8.4
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://www.nano-editor.org/dist/v$MAJOR/nano-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build




make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


