#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.15.1
URL=https://github.com/containers/netavark/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=netavark-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

make PREFIX=/usr build -j22


# Install
make PREFIX=/usr DESTDIR=/pkgs/$PACKAGE install
cd /pkgs



sudo echo "libgcc aardvark-dns" > /pkgs/$PACKAGE/depends
sudo echo "rustc git protobuf" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished
# Method 2 install
cp -rpv /pkgs/$PACKAGE/* /
cd /blfs/builds
sudo rm -r $DIR


