#!/bin/bash

export CFLAGS="-O2"
export CXXFLAGS="-O2"

PKG_VER=1.52.1
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/releases/$PKG_VER/downloads/NetworkManager-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=network-manager

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


grep -rl '^#!.*python$' | xargs sed -i '1s/python/&3/'

mkdir build
cd build


meson --prefix=/usr              \
      --buildtype=release        \
      -Dlibaudit=no              \
      -Dnmtui=true               \
      -Dnetconfig=no \
      -Dconfig_dns_rc_manager_default=symlink \
      -Dovs=false                \
      -Dppp=false                \
      -Dselinux=false            \
      -Dqt=false                 \
      -Dsession_tracking=systemd \
      -Dmodem_manager=false \
      ..
ninja






# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs


sudo echo "libpsl jansson libndp dhcpcd iptables newt nss pygobject3 systemd upower wpa_supplicant curl" > /pkgs/$PACKAGE/depends
sudo echo "modem-manager" > /pkgs/$PACKAGE/make-depends
sudo echo "systemctl disable NetworkManager-wait-online" > /pkgs/$PACKAGE/postinst
cat > /pkgs/$PACKAGE/etc/NetworkManager/NetworkManager.conf << "EOF"
[main]
plugins=keyfile
EOF
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo echo "/etc/NetworkManager/NetworkManager.conf" > /pkgs/$PACKAGE/backup
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


