#!/bin/bash

export CFLAGS="-O2"
export CFLAGS+=" -Wno-error=deprecated-declarations"
export CXXFLAGS="-O2"
PKG_VER=31.1.1
set -e
URL=https://github.com/obsproject/obs-studio/releases/download/$PKG_VER/OBS-Studio-$PKG_VER-Sources.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=obs-studio-$PKG_VER-sources
PACKAGE=obs-studio

# Get Package

cd /blfs/builds
wget $URL
# NVENC headers, obs refuses to build without them, if anyone finds an issue with the version being too old file an issue to update, at build time, obs does not like versions > 12.2.x.x
wget https://github.com/FFmpeg/nv-codec-headers/releases/download/n12.1.14.0/nv-codec-headers-12.1.14.0.tar.gz
tar -xvf $TAR
cd $DIR

# Build

tar -xf ../nv-codec-headers-12.1.14.0.tar.gz
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_BROWSER=OFF \
    -DFFnvcodec_INCLUDE_DIR="../nv-codec-headers-12.1.14.0/include/" \
    -DENABLE_VLC=OFF \
    -DENABLE_NEW_MPEGTS_OUTPUT=OFF \
    -DENABLE_AJA=OFF \
    -DENABLE_WEBSOCKET=OFF \
    -DENABLE_VST=OFF \
    -DENABLE_QSV11=OFF \
    -DENABLE_WEBRTC=OFF \
    -DCALM_DEPRECATION=ON \
    -Wno-dev ..


make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "mbedtls uthash qt6 ffmpeg luajit llvm xorg" > /pkgs/$PACKAGE/depends
sudo echo "ecm mbedtls nlohmann-json swig" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


