#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=6.1
URL=https://freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja

# Install
DESTDIR=/pkgs/$PACKAGE ninja install
ninja install
cd /pkgs



sudo echo "gtkmm4 glibmm json-glib libcanberra libsigc++2 pulseaudio" > /pkgs/$PACKAGE/depends
sudo echo "lynx gtkmm4 glibmm json-glib libcanberra libsigc++2 pulseaudio" > /pkgs/$PACKAGE/make-depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


