#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=31.0
URL=https://github.com/protocolbuffers/protobuf/releases/download/v$PKG_VER/protobuf-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

# Build python module first
cd python
python3 setup.py build
cd ..

mkdir build
cd build


cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_BUILD_TYPE=Release       \
      -DCMAKE_SKIP_INSTALL_RPATH=ON    \
      -Dprotobuf_BUILD_TESTS=OFF       \
      -Dprotobuf_BUILD_SHARED_LIBS=ON  \
      -G Ninja ..

ninja



# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
# python module
cd python
python3 setup.py install --skip-build --root="/pkgs/$PACKAGE"
# no read perms?
chmod +r /pkgs/$PACKAGE/usr/lib/python*/site-packages/*/*



cd /pkgs



sudo echo "abseil-cpp" > /pkgs/$PACKAGE/depends
sudo echo "python setuptools wheel cmake" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


