#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=17.0
URL=https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

meson setup --prefix=/usr       \
      --buildtype=release \
      -Ddatabase=gdbm     \
      -Ddoxygen=false    ..


ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo rm /pkgs/$PACKAGE/usr/share/dbus-1/system.d/pulseaudio-system.conf
cd /pkgs
rm -vf /pkgs/$PACKAGE/etc/xdg/autostart/pulseaudio.desktop         &&
rm -vf /pkgs/$PACKAGE/etc/xdg/Xwayland-session.d/00-pulseaudio-x11 &&
sed -e '$a autospawn = no' -i /pkgs/$PACKAGE/etc/pulse/client.conf


sudo echo "wireplumber libsndfile alsa-lib dbus glib libcap xorg-libs speex" > /pkgs/$PACKAGE/depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR



