#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=6.9.1
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.qt.io/official_releases/qt/$MAJOR/$PKG_VER/submodules/qtwebengine-everywhere-src-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build



cmake -DCMAKE_MESSAGE_LOG_LEVEL=STATUS             \
      -DQT_FEATURE_webengine_system_ffmpeg=ON      \
      -DQT_FEATURE_webengine_system_icu=ON         \
      -DQT_FEATURE_webengine_system_libevent=ON    \
      -DQT_FEATURE_webengine_proprietary_codecs=ON \
      -DQT_FEATURE_webengine_webrtc_pipewire=ON    \
      -DQT_BUILD_EXAMPLES_BY_DEFAULT=OFF           \
      -DQT_GENERATE_SBOM=OFF                       \
      -G Ninja ..     

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "cups qt6 nss libxml2 ffmpeg fontconfig harfbuzz pipewire pulseaudio icu libwebp opus libevent" > /pkgs/$PACKAGE/depends
sudo echo "nodejs python-html5lib pciutils" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR

