#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=1.3.0
URL=https://github.com/opencontainers/runc/releases/download/v$PKG_VER/runc.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=runc-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

make runc -j22


# Install
install -Dm755 runc /pkgs/$PACKAGE/usr/bin/runc
install -Dm644 contrib/completions/bash/runc \
    /pkgs/$PACKAGE/usr/share/bash-completion/completions/runc
cd /pkgs




sudo echo "libseccomp criu" > /pkgs/$PACKAGE/depends
sudo echo "git go" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


