#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=1.86.0
URL=https://static.rust-lang.org/dist/rustc-$PKG_VER-src.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=rustc
set -e
# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


cat << EOF > config.toml

# credit to LFS
# tell x.py to not keep printing an annoying warning
change-id = 131075
[llvm]
# by default, rust will build for a myriad of architectures
targets = "X86"

# When using system llvm prefer shared libraries
link-shared = true

download-ci-llvm = false

[build]
docs = false

# install cargo as well as rust
extended = true


# Do not query new versions of dependencies online.
locked-deps = true

tools = ["cargo", "clippy", "rustdoc", "rustfmt"]

vendor = true


[install]
prefix = "/usr"
docdir = "share/doc/rustc"

[rust]
channel = "stable"
rpath = false
lto = "thin"
lld = false
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"

EOF

python3 ./x.py build --exclude src/tools/miri




# Install

export LIBSSH2_SYS_USE_PKG_CONFIG=1 &&
DESTDIR=${PWD}/install python3 ./x.py install &&
unset LIBSSH2_SYS_USE_PKG_CONFIG

chown -R root:root install
mkdir -p /pkgs/rustc/
cp -a install/* /pkgs/rustc

# Host install method 2 
cp -a install/* /



cd /pkgs



sudo echo "curl gcc clang libssh2" > /pkgs/$PACKAGE/depends
sudo echo "llvm curl libssh2 cmake gcc clang" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


