#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
set -e

PKG_VER=2.32.51
URL=https://github.com/libsdl-org/sdl2-compat/releases/download/release-$PKG_VER/sdl2-compat-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=sdl2-compat

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=release ..

make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
ln -s sdl2_compat.pc /pkgs/$PACKAGE/usr/lib/pkgconfig/sdl2.pc
ln -s sdl2_compat.pc /usr/lib/pkgconfig/sdl2.pc
cd /pkgs



sudo echo "sdl3 libxkbcommon wayland-protocols xorg-libs alsa-lib nasm" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


