#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2025.05
URL=https://github.com/thesofproject/sof-bin/releases/download/v$PKG_VER/sof-bin-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=sof-firmware

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build





# Install
mkdir -p /pkgs/$PACKAGE/usr/lib/firmware/intel
cp -a sof* /pkgs/$PACKAGE/usr/lib/firmware/intel
cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "coreutils util-linux" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


