#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=4.6.1
URL=https://github.com/plougher/squashfs-tools/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=squashfs-tools-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

cd squashfs-tools

make \
 GZIP_SUPPORT=1 \
 XZ_SUPPORT=1 \
 ZSTD_SUPPORT=1 \
 LZMA_XZ_SUPPORT=1 \
 XZ_SUPPORT=1 \
 LZ4_SUPPORT=1 \
 XATTR_SUPPORT=1 \
 -j16


# Install
sudo make INSTALL_PREFIX=/pkgs/$PACKAGE/usr install
sudo make install
cd /pkgs



sudo echo "lzo lz4 zstd xz zlib libgcc" > /pkgs/$PACKAGE/depends
sudo echo "lzo lz4 zstd xz zlib libgcc" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


