#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=v2025.122.141614
URL=https://github.com/LizardByte/Sunshine.git
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=Sunshine
PACKAGE=sunshine

# Get Package

cd /blfs/builds
git clone https://github.com/LizardByte/Sunshine.git
cd $DIR
git checkout tags/$PKG_VER
git submodule update --init --recursive

# Build

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=release -G Ninja ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "libayatana-appindicator libcap libdrm mesa evdev icu miniupnpc libnotify pulseaudio libva opus wayland" > /pkgs/$PACKAGE/depends
sudo echo "intel-media-driver gcc boost cmake git nodejs" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


