#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2025.122.141614
URL=https://github.com/LizardByte/Sunshine.git
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=Sunshine
PACKAGE=sunshine

# Get Package

cd /blfs/builds
git clone https://github.com/LizardByte/Sunshine.git
cd $DIR
git checkout tags/$PKG_VER
git submodule update --init --recursive

# Build

# System boost fix
sed -E 's&<boost/process.hpp>&"/blfs/builds/'"$DIR"'/boost_process_v1.hpp"&' \
  -i /blfs/builds/$DIR/src/platform/common.h

sed -E 's&(namespace bp = boost::process);&\1::v1;&' \
  -i /blfs/builds/$DIR/src/platform/linux/misc.cpp

sed -E 's&<boost/process/v1.hpp>&"/blfs/builds/'"$DIR"'/boost_process_v1.hpp"&' \
  -i /blfs/builds/$DIR/src/platform/linux/misc.cpp \
  /blfs/builds/$DIR/src/process.h

install -Dm644 /dev/stdin "boost_process_v1.hpp" << END
#ifndef BOOST_PROCESS_V1_HPP
#define BOOST_PROCESS_V1_HPP
#include <boost/process/v1/args.hpp>
#include <boost/process/v1/async.hpp>
#include <boost/process/v1/async_system.hpp>
#include <boost/process/v1/group.hpp>
#include <boost/process/v1/child.hpp>
#include <boost/process/v1/cmd.hpp>
#include <boost/process/v1/env.hpp>
#include <boost/process/v1/environment.hpp>
#include <boost/process/v1/error.hpp>
#include <boost/process/v1/exe.hpp>
#include <boost/process/v1/group.hpp>
#include <boost/process/v1/handles.hpp>
#include <boost/process/v1/io.hpp>
#include <boost/process/v1/pipe.hpp>
#include <boost/process/v1/shell.hpp>
#include <boost/process/v1/search_path.hpp>
#include <boost/process/v1/spawn.hpp>
#include <boost/process/v1/system.hpp>
#include <boost/process/v1/start_dir.hpp>
#endif //BOOST_PROCESS_V1_HPP
END

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=release \
      -DBUILD_DOCS=OFF \
      -DSUNSHINE_ASSETS_DIR="share/sunshine" \
      -DSUNSHINE_EXECUTABLE_PATH='/usr/bin/sunshine' \
      -DBoost_USE_STATIC_LIBS=OFF \
      -DSUNSHINE_ENABLE_DRM=ON \
      -DSUNSHINE_ENABLE_TRAY=ON \
      -DSUNSHINE_ENABLE_VAAPI=ON \
      -DSUNSHINE_ENABLE_WAYLAND=ON \
      -DSUNSHINE_ENABLE_X11=ON \
      -DSUNSHINE_ENABLE_CUDA=OFF \
      -G Ninja ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo setcap -r /pkgs/$PACKAGE/usr/bin/sunshine
cd /pkgs



sudo echo "numactl libayatana-appindicator libcap libdrm mesa libevdev icu miniupnpc libnotify pulseaudio libva opus wayland" > /pkgs/$PACKAGE/depends
sudo echo "intel-media-driver gcc boost cmake git nodejs" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


