#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=8.6.14
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://cytranet.dl.sourceforge.net/project/tcl/Tcl/$PKG_VER/tk$PKG_VER-src.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=tk$PKG_VER
PACKAGE=tk

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
cd unix

./configure \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--enable-threads \
		--disable-rpath \
		--enable-64bit

make 


sed -e "s@^\(TK_SRC_DIR='\).*@\1/usr/include'@" \
    -e "/TK_B/s@='\(-L\)\?.*unix@='\1/usr/lib@" \
    -i tkConfig.sh
# Install
sudo make INSTALL_ROOT=/pkgs/$PACKAGE install
sudo make INSTALL_ROOT=/pkgs/$PACKAGE install-private-headers
chmod -v 755 /pkgs/$PACKAGE/usr/lib/libtk$MAJOR.so
mkdir -p /pkgs/$PACKAGE/usr/bin/
ln -v -sf wish$MAJOR /pkgs/$PACKAGE/usr/bin/wish
cd /pkgs



sudo echo "tcl" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


