#!/bin/bash
# heavily inspired on arch's build script
export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2.37
URL=https://sourceforge.net/projects/dejavu/files/dejavu/$PKG_VER/dejavu-fonts-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=ttf-dejavu

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



make full-ttf -j22


# Install
install -Dm0644 -t /pkgs/$PACKAGE/usr/share/fonts/TTF build/*.ttf
install -Dm0644 -t /pkgs/$PACKAGE/usr/share/fonts/conf.avail fontconfig/*.conf
mkdir -p /pkgs/$PACKAGE/usr/share/fontconfig/conf.avail
ln -srt /pkgs/$PACKAGE/usr/share/fontconfig/conf.default /pkgs/$PACKAGE/usr/share/fontconfig/conf.avail/*


cd /pkgs



sudo echo "" > /pkgs/$PACKAGE/depends
sudo echo "fontforge git perl-font-ttf" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


