#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=5.9.2
URL=https://github.com/microsoft/TypeScript/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=TypeScript-$PKG_VER
PACKAGE=typescript

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
npm ci
npm i -D hereby
npx hereby LKG


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib/node_modules/$PACKAGE
mkdir -p /pkgs/$PACKAGE/usr/bin

rsync -r --exclude=.gitattributes bin lib package.json /pkgs/$PACKAGE/usr/lib/node_modules/$PACKAGE
ln -sfv /usr/lib/node_modules/TypeScript/{tsc,tsserver} /pkgs/$PACKAGE/usr/bin

cd /pkgs



sudo echo "nodejs" > /pkgs/$PACKAGE/depends
sudo echo "nodejs rsync git" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


