#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
#HOLD_TUCANA
#NO_CURRENCY
# This hasn't been updated in 6 years
PKG_VER=0.3.12
URL=https://pagure.io/volume_key/archive/volume_key-$PKG_VER/volume_key-volume_key-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=volume-key

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
# credit archlinux
autoreconf -fiv
# fix build error
find . -name ".pyc" -delete
export CFLAGS+=" $(python3-config --includes)"
./configure --prefix=/usr
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool



make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "glib gpgme nspr nss cryptsetup" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


