#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

#HOLD_TUCANA

# 1.3 for most things, nothing needs 2 yet
PKG_VER=1.3
URL=https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing/-/archive/v$PKG_VER/webrtc-audio-processing-v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://gitlab.archlinux.org/archlinux/packaging/packages/webrtc-audio-processing-1/-/raw/main/0001-Fix-compilation-with-GCC-15.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../0001-Fix-compilation-with-GCC-15.patch
mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "abseil-cpp" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


