#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=2.2.1
URL=https://github.com/bugaevc/wl-clipboard/archive/refs/tags/v$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=wl-clipboard-$PKG_VER
PACKAGE=wl-clipboard

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "wayland" > /pkgs/$PACKAGE/depends
sudo echo "bash-completion wayland-protocols meson ninja xorg" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


