#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
#ARCH_PKG=yarn
#ARCH_VAR=pkgver
PKG_VER=1.22.22
URL=https://registry.npmjs.org/yarn/-/yarn-$PKG_VER.tgz
TAR=$(echo $URL | sed -r 's|(.*)/||')
PACKAGE=yarn

# Get Package

cd /blfs/builds
wget $URL

# Build
# Install
npm install -g --prefix /pkgs/$PACKAGE/usr /blfs/builds/$TAR
chmod -R u=rwX,go=rX /pkgs/$PACKAGE
cd /pkgs
mkdir -p /pkgs/$PACKAGE/usr/share/licenses/$PACKAGE
ln -s "../../../lib/node_modules/$PACKAGE/LICENSE" "/pkgs/$PACKAGE/usr/share/licenses/$PACKAGE/"


sudo echo "nodejs" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp -rp /pkgs/$PACKAGE/* /
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds


