#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=0.9.3+16.04.20160218
URL=https://launchpad.net/ubuntu/+archive/primary/+files/libdbusmenu-qt_$PKG_VER.orig.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=libdbusmenu-qt-$PKG_VER
PACKAGE=libdbusmenu-qt

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build



mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -DWITH_DOC=OFF              \
      -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
      -Wno-dev ..





make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "qt5" > /pkgs/$PACKAGE/depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


