#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PACKAGE=plasma-vault
PKG_VER=6.3.4
URL=https://download.kde.org/stable/plasma/$PKG_VER/$PACKAGE-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')


# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed -i '/^#include/ a #include <QDebug>' kded/engine/commandresult.h

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release         \
      -DBUILD_TESTING=OFF                \
      -Wno-dev ..





make -j22


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "plasma-activities kconfig kcoreaddons kdbusaddons ki18n kio kirigami kitemmodels kservice kwidgetsaddons libksysguard libplasma plasma-workspace qt6" > /pkgs/$PACKAGE/depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


