#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=4.20.1
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://archive.xfce.org/src/xfce/libxfce4util/$MAJOR/libxfce4util-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
autoreconf -fiv
./configure --prefix=/usr --enable-maintainer-mode --disable-debug --sysconfdir=/etc --localstatedir=/var


make
make check
# Install
sudo DESTDIR=/pkgs/$PACKAGE make install
sudo make install
cd /pkgs



sudo echo "glib" > /pkgs/$PACKAGE/depends
sudo echo "vala gobject-introspection" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


