#!/bin/bash
PACKAGE=xfce4
PKG_VER=4.20.0
export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
bash libxfce4util
bash xfconf
bash libxfce4ui
bash ../exo
bash garcon
bash xfce4-panel
bash thunar
bash thunar-volman
bash tumbler
bash xfce4-appfinder
bash xfce4-power-manager
bash xfce4-settings
bash xfdesktop
bash xfwm4
bash xfce4-session
bash parole
bash xfce4-terminal
bash xfce4-notifyd
bash xfce4-pulseaudio-plugin  

mkdir -p /pkgs/$PACKAGE
echo "xfce4-session xfce4-panel tumbler xfwm4 xfce4-settings xfce4-power-manager thunar" > /pkgs/$PACKAGE/depends
cd /pkgs
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
tar -cvzpf $PACKAGE.tar.xz $PACKAGE
cp $PACKAGE.tar.xz /finished/

