#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=0.3.2
URL=https://github.com/lxde/lxrandr/archive/refs/tags/$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=lxrandr-$PKG_VER
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
autoupdate
autoreconf -fiv
# we don't build the gtk2 version
./configure --prefix=/usr --sysconfdir=/etc --enable-gtk3


make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "xorg" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


