#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

set -e
PKG_VER=48.0
MAJOR=$(echo $PKG_VER | sed "s|.[^.]*$||g")
URL=https://download.gnome.org/sources/evince/$MAJOR/evince-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&



export CPPFLAGS="-I/opt/texlive/2024/include" &&
export LDFLAGS="$LDFLAGS -L/opt/texlive/2024/lib"
meson --prefix=/usr          \
      --buildtype=release    \
      -Dgtk_doc=false          \
      --wrap-mode=nodownload \
      ..


ninja 


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "adwaita gsettings-desktop-schemas gtk3 itstool libhandy libxml2 openjpeg gnome-keyring gobject-introspection libarchive libsecret poppler" > /pkgs/$PACKAGE/depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


