#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=49
MAJOR=$(echo $PKG_VER | sed "s|.[^.]*$||g")
URL=https://download.gnome.org/sources/gnome-session/$MAJOR/gnome-session-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gnome-session

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed 's@/bin/sh@/bin/sh -l@' -i gnome-session/gnome-session.in
mkdir build &&
cd    build &&


meson setup --prefix=/usr --buildtype=release .. 

ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install


rm -v /pkgs/$PACKAGE/usr/share/xsessions/gnome.desktop
rm -v /pkgs/$PACKAGE/usr/share/wayland-sessions/gnome.desktop
cd /pkgs


sudo echo "xdg-desktop-portal-gnome dbus-glib gnome-desktop json-glib mesa systemd upower" > /pkgs/$PACKAGE/depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


