#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=48.1
PACKAGE=gnome

# Get Package

cd /blfs/builds

# Build





mkdir -p /pkgs/$PACKAGE/var/cache/neptune/meta-pkgs
# Install
cd /pkgs



sudo echo "gnome-font-viewer xdg-desktop-portal-gnome polkit-gnome gcr gsettings-desktop-schemas libsecret rest totem-pl-parser yelp-xsl geocode-glib gjs gnome-autoar gnome-desktop gnome-menus gnome-video-effects gnome-online-accounts gvfs libchamplain libgdata libgtop libgweather libpeas libwnck network-manager folks evolution-data-server gsound dconf gnome-backgrounds nautilus gexiv2 zenity gnome-bluetooth gnome-keyring gnome-settings-daemon gnome-control-center mutter gnome-shell gnome-shell-extensions gnome-session snapshot eog file-roller gnome-calculator gnome-disk-util gnome-logs gnome-maps gnome-nettool gnome-power-manager gnome-screenshot gnome-system-monitor gnome-terminal gnome-weather gtk4 gnome-icon-theme adwaita xdg-user-dirs xorg gdm gnome-browser-connector gedit gnome-software" > /pkgs/$PACKAGE/depends
sudo echo "gdk-pixbuf-query-loaders --update-cache" > /pkgs/$PACKAGE/postinst
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished




