#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=48.1
MAJOR=$(echo $PKG_VER | sed "s|.[^.]*$||g")
URL=https://download.gnome.org/sources/gnome-user-docs/$MAJOR/gnome-user-docs-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gnome-user-docs

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr &&
make -j16


# Install
make install
make DESTDIR=/pkgs/$PACKAGE install
cd /pkgs


sudo echo "itstool libxml2" > /pkgs/$PACKAGE/depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


