#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"



PKG_VER=48.0
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://download.gnome.org/sources/gnome-keyring/$MAJOR/gnome-keyring-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=gnome-keyring

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i 's:"/desktop:"/org:' schema/*.xml
mkdir gbuild
cd gbuild
meson setup --prefix=/usr --buildtype=release -Dssh-agent=true ..
ninja


# Install
ninja install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "dbus gcr-4 libxslt gnupg pam" > /pkgs/$PACKAGE/depends
sudo echo "openssh" > /pkgs/$PACKAGE/make-depends
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


