#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=48.1
MAJOR=$(echo $PKG_VER | sed "s|.[^.]*$||g")
URL=https://download.gnome.org/sources/gnome-system-monitor/$MAJOR/gnome-system-monitor-$PKG_VER.tar.xz
CAT=gnome
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
find . -name meson.build | xargs sed -i -e '/catch2/d' &&
sed -i '152,162d' src/meson.build
mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..
ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs



sudo echo "libadwaita gtkmm4 gtk4 libsigc++ itstool libgtop librsvg desktop-file-utils" > /pkgs/$PACKAGE/depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


