#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=48.2
MAJOR=$(echo $PKG_VER | sed "s|.[^.]*$||g")
URL=https://download.gnome.org/sources/gnome-maps/$MAJOR/gnome-maps-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&


meson setup --prefix=/usr --buildtype=release .. &&

ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs


sudo echo "protobuf-c desktop-file-utils folks geoclue geocode-glib gjs libchamplain libgweather libgee libhandy rest libshumate geocode-glib-2" > /pkgs/$PACKAGE/depends
sudo echo "gnome" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


