#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=16.0.2
MAJOR=$(echo $PKG_VER | sed "s|.[^.]*$||g")
URL=https://gitlab.gnome.org/GNOME/gucharmap/-/archive/$PKG_VER/gucharmap-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
wget https://www.unicode.org/Public/zipped/16.0.0/UCD.zip
wget https://www.unicode.org/Public/zipped/16.0.0/Unihan.zip
tar -xvf $TAR
cd $DIR

# Build

mkdir build &&
cd    build &&

mkdir ucd                     &&
pushd ucd                     &&
  unzip ../../../UCD.zip      &&
  cp -v ../../../Unihan.zip . &&
popd                          &&

meson setup --prefix=/usr       \
            --strip             \
            --buildtype=release \
            -D ucd_path=./ucd   \
            -D docs=false       \
            .. 
ninja -j16


# Install
ninja install && DESTDIR=/pkgs/$PACKAGE ninja install

cd /pkgs


sudo echo "accounts-service gtk3 iso-codes itstool libcanberra libdaemon keyutils inetutils" > /pkgs/$PACKAGE/depends
sudo echo "unzip" > /pkgs/$PACKAGE/make-depends
sudo echo "glib-compile-schemas /usr/share/glib-2.0/schemas" > /pkgs/$PACKAGE/postinst
sudo rm -rf /pkgs/$PACKAGE/blfs
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


