#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "
PKG_VER=1.2.3
URL=https://github.com/linuxwacom/xf86-input-wacom/releases/download/xf86-input-wacom-$PKG_VER/xf86-input-wacom-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build

./configure --prefix=/usr --sysconfdir=/etc

make -j22

# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs



sudo echo "libwacom xorg-server" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


