#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=2.45
URL=https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build




mkdir build &&
cd    build &&

meson setup --prefix=/usr --buildtype=release -Dcompat-rules=true -Dxorg-rules-symlinks=true  -Dxkb-base="/usr/share/X11/xkb"..

ninja

# Install
DESTDIR=/pkgs/$PACKAGE ninja install
cd /pkgs



sudo echo "xorg-libs" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


