#!/bin/bash
sudo neptune install --y bison gperf pkgconf cmake make
bash -e kirigami
bash -e ktexttemplate
bash -e kuserfeedback
bash -e attica
bash -e kapidox
bash -e karchive
bash -e kcodecs
bash -e kconfig
bash -e kcoreaddons
bash -e kdbusaddons
bash -e kdnssd
bash -e kguiaddons
bash -e ki18n
bash -e kcolorscheme
bash -e ksvg
bash -e kidletime
bash -e kimageformats
bash -e kitemmodels
bash -e kitemviews
bash -e kplotting
bash -e kwidgetsaddons
bash -e kwindowsystem
bash -e kstatusnotifieritem
bash -e networkmanager-qt
bash -e solid
bash -e sonnet
bash -e threadweaver
bash -e kauth
bash -e kcompletion
bash -e kcrash
bash -e kdoctools
bash -e kpty
bash -e kunitconversion
bash -e kconfigwidgets
bash -e kservice
bash -e kglobalaccel
bash -e kpackage
bash -e breeze-icons
bash -e kdesu
bash -e kiconthemes
bash -e knotifications
bash -e kjobwidgets
bash -e ktextwidgets
bash -e kxmlgui
bash -e kbookmarks
bash -e kwallet
bash -e kded
bash -e kio
bash -e kdeclarative
bash -e kcmutils
bash -e syndication
bash -e knewstuff
bash -e frameworkintegration
bash -e kparts
bash -e syntax-highlighting
bash -e ktexteditor
bash -e modemmanager-qt
bash -e kcontacts
bash -e kpeople
bash -e bluez-qt
bash -e kfilemetadata
bash -e baloo
bash -e krunner
bash -e prison
bash -e qqc2-desktop-style
bash -e kholidays
bash -e purpose
bash -e kcalendarcore
bash -e kquickcharts
bash -e knotifyconfig
bash -e kdav
