#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=8.3.0
URL=https://files.pythonhosted.org/packages/source/s/sphinx/sphinx-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
python3 -m build --wheel --skip-dependency-check



# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl

cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python-roman-numerals-py python-alabaster python-babel python-docutils python-imagesize python-packaging pygments python-requests python-snowballstemmer python-sphinxcontrib-applehelp python-sphinxcontrib-devhelp python-sphinxcontrib-htmlhelp python-sphinxcontrib-jsmath python-sphinxcontrib-qthelp python-sphinxcontrib-serializinghtml" > /pkgs/$PACKAGE/depends
sudo echo "python-build python-installer" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


