#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=6.0.1
URL=https://files.pythonhosted.org/packages/source/P/PyYAML/PyYAML-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=pyyaml

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build


python3 -m build --wheel --skip-dependency-check --config-setting=--with-libyaml



# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl
cd /pkgs

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "python libyaml" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


