#!/bin/bash


PKG_VER=9.7
URL=https://ftp.gnu.org/gnu/coreutils/coreutils-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
set -e

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR


# Build
autoreconf -fv
automake -af
export FORCE_UNSAFE_CONFIGURE=1
./configure --prefix=/usr                     \
	--enable-install-program=hostname \
        --enable-no-install-program=kill,uptime

make -j16


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install

mkdir -p /pkgs/coreutils/usr/sbin
mv -v /usr/bin/chroot /usr/sbin
mv -v /pkgs/coreutils/usr/bin/chroot /pkgs/coreutils/usr/sbin

cd /pkgs



sudo echo "gettext glibc gmp grep libcap openssl attr acl" > /pkgs/$PACKAGE/depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


