#!/bin/bash

set -e
export CFLAGS="-O2"
export CXXFLAGS="-O2"
#ARCH_PKG=elfutils
#ARCH_VAR=pkgver
PKG_VER=0.192
URL=https://sourceware.org/ftp/elfutils/$PKG_VER/elfutils-$PKG_VER.tar.bz2
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=libelf
ALT_PACKAGE=elfutils

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure --prefix=/usr                \
            --disable-debuginfod         \
	    --sysconfdir=/etc \
	    --program-prefix="eu-" \
            --enable-libdebuginfod=dummy


make -j16


# Install
sudo make DESTDIR=/pkgs/$ALT_PACKAGE install

# libelf
mkdir -p /pkgs/$PACKAGE/etc/profile.d
mkdir -p /pkgs/$PACKAGE/usr/{include,lib}
mv /pkgs/$ALT_PACKAGE/usr/lib/* /pkgs/$PACKAGE/usr/lib/
mv /pkgs/$ALT_PACKAGE/usr/include/* /pkgs/$PACKAGE/usr/include/
mv /pkgs/$ALT_PACKAGE/etc/profile.d/* /pkgs/$PACKAGE/etc/profile.d
# manpages in main elfutils package


install -vm644 config/libelf.pc /pkgs/$PACKAGE/usr/lib/pkgconfig
rm /pkgs/$PACKAGE/usr/lib/libelf.a
cd /pkgs


# libelf
sudo echo "glibc zlib" > /pkgs/$PACKAGE/depends
sudo echo "" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished

# elfutils
sudo echo "libelf" > /pkgs/$ALT_PACKAGE/depends
sudo echo "" > /pkgs/$ALT_PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$ALT_PACKAGE/version
sudo tar -cvzpf $ALT_PACKAGE.tar.xz $ALT_PACKAGE
sudo cp $ALT_PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR

cp -rpv /pkgs/$PACKAGE/* /
cp -rpv /pkgs/$ALT_PACKAGE/* /
