#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=6.14
URL=https://www.kernel.org/pub/linux/docs/man-pages/man-pages-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

rm -v man3/crypt*
# Install
sudo make -R GIT=false prefix=/usr DESTDIR=/pkgs/$PACKAGE install
cd /pkgs



sudo echo "libpipeline" > /pkgs/$PACKAGE/depends
sudo echo "make sed gcc coreutils" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


