#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"

PKG_VER=0.2.2
URL=https://github.com/Tucana-Linux/neptune/releases/download/$PKG_VER/neptune-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=neptune

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
python3 -m build --wheel --skip-dependency-check
mkdir -p doc
cd doc
wget https://raw.githubusercontent.com/Tucana-Linux/neptune/refs/tags/$PKG_VER/doc/repositories.yaml
wget https://raw.githubusercontent.com/Tucana-Linux/neptune/refs/tags/$PKG_VER/doc/config.yaml
cd ..

# Install
sudo python3 -m installer --destdir=/pkgs/$PACKAGE  dist/*.whl

cd /pkgs

# make inital directories
mkdir -p /pkgs/$PACKAGE/var/lib/neptune/cache/depend
mkdir -p /pkgs/$PACKAGE/var/lib/neptune/file-lists
mkdir -p /pkgs/$PACKAGE/etc/neptune
mkdir -p /pkgs/$PACKAGE/usr/share/doc/neptune/

# base config
cp /blfs/builds/$DIR/doc/config.yaml /pkgs/$PACKAGE/etc/neptune
cp /blfs/builds/$DIR/doc/repositories.yaml /pkgs/$PACKAGE/etc/neptune

sudo echo "python-packaging pyyaml python-rich python-requests" > /pkgs/$PACKAGE/depends
sudo echo "python-build python-installer" > /pkgs/$PACKAGE/make-depends
sudo cat > /pkgs/$PACKAGE/backup << EOF
/etc/neptune/config.yaml
/etc/neptune/repositories.yaml
EOF
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


