#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"
PKG_VER=3.13.5
URL=https://www.python.org/ftp/python/$PKG_VER/Python-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=python

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 < ../133944.patch
./configure --prefix=/usr        \
            --enable-shared      \
            --with-system-expat  \
            --with-system-ffi    \
            --enable-optimizations \
            --with-ensurepip=install \





make -j20


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
cd /pkgs
mkdir -p /pkgs/$PACKAGE/etc
cat > /pkgs/$PACKAGE/etc/pip.conf << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

# For some reason pip does not install by default even with ensurepip on
curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --ignore-installed --root=/pkgs/$PACKAGE
rm get-pip.py

# Add python symlink
ln -sfv /usr/bin/python /pkgs/$PACKAGE/usr/bin/python3

sudo cp -rpv /pkgs/$PACKAGE/* /

sudo echo "bzip2 expat libffi zlib openssl sqlite libxcrypt" > /pkgs/$PACKAGE/depends
sudo echo "tk" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


