#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


set -e

PKG_VER=257.5
URL=https://github.com/systemd/systemd/archive/v$PKG_VER/systemd-$PKG_VER.tar.gz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build
sed -i -e 's/GROUP="render"/GROUP="video"/' \
       -e 's/GROUP="sgx", //' rules.d/50-udev-default.rules.in

mkdir build
cd build

meson setup --prefix=/usr                 \
      --buildtype=release           \
      -Ddefault-dnssec=no           \
      -Dfirstboot=false             \
      -Dinstall-tests=false         \
      -Ddev-kvm-mode=0660     \
      -Dfallback-hostname="tucana" \
      -Dman=enabled                    \
      -Dsysusers=false              \
      -Drpmmacrosdir=no             \
      -Dhomed=false                 \
      -Duserdb=false                \
      -Ddefault-locale='C.UTF-8' \
      -Dlocalegen-path=/usr/bin/locale-gen \
      -Dmode=release                \
      -Dpam=true                    \
      -Dpamconfdir=/etc/pam.d       \
      -Dsbat-distro="tucana" \
      -Dsbat-distro-url="https://tucanalinux.org/" \
      ..      
      
ninja


# Install
sudo  DESTDIR=/pkgs/$PACKAGE ninja install
sudo ninja install
cd /pkgs
cat > /pkgs/$PACKAGE/etc/pam.d/systemd-user << "EOF"
# Begin /etc/pam.d/systemd-user

account  required    pam_access.so
account  include     system-account

session  required    pam_env.so
session  required    pam_limits.so
session  required    pam_unix.so
session  required    pam_loginuid.so
session  optional    pam_keyinit.so force revoke
session  optional    pam_systemd.so

auth     required    pam_deny.so
password required    pam_deny.so

# End /etc/pam.d/systemd-user
EOF

# Needed for steam to run
ln -s /usr/lib/libudev.so.1 /pkgs/$PACKAGE/usr/lib/libudev.so.0
echo "KEYMAP=us" > /pkgs/$PACKAGE/etc/vconsole.conf

sudo echo "kbd cryptsetup pam glibc util-linux libcap acl attr libidn2 libseccomp iptables dbus libgcrypt p11-kit libxcrypt" > /pkgs/$PACKAGE/depends
sudo echo "gperf pam glibc util-linux libcap acl attr gnu-efi jinja" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvzpf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


