#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PKG_VER=2.41.3
# changed from the usual because they don't do .0 versions
MAJOR=$(echo $PKG_VER | sed '/\..*\./ s/\.[^.]*$//')
URL=https://www.kernel.org/pub/linux/utils/util-linux/v$MAJOR/util-linux-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
            --bindir=/usr/bin    \
            --libdir=/usr/lib    \
            --sbindir=/usr/sbin  \
            --disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-pylibmount \
            --disable-static     \
            --without-python


make 


# Install
sudo make DESTDIR=/pkgs/$PACKAGE install
sudo make install
cd /pkgs
# Runuser pam configs
mkdir -p /pkgs/$PACKAGE/etc/pam.d
cat > /pkgs/$PACKAGE/etc/pam.d/runuser << EOF
#%PAM-1.0
auth		sufficient	pam_rootok.so
session		optional	pam_keyinit.so revoke
session		required	pam_limits.so
session		required	pam_unix.so
EOF
cat > /pkgs/$PACKAGE/etc/pam.d/runuser-l << EOF
#%PAM-1.0
auth		include		runuser
session		optional	pam_keyinit.so force revoke
session		optional	pam_systemd.so
session		include		runuser
EOF


sudo echo "libxcrypt glibc libcap ncurses readline zlib" > /pkgs/$PACKAGE/depends
sudo echo "bash binutils coreutils diffutils findutils gawk libgcc gettext glibc grep libcap make ncurses sed zlib" > /pkgs/$PACKAGE/make-depends

sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


