#!/bin/bash
bash -e qca-qt5
bash -e attica5
bash -e karchive5
bash -e kcodecs5
bash -e kconfig5
bash -e kcoreaddons5
bash -e kdbusaddons5
bash -e kguiaddons5
bash -e ki18n5
bash -e kitemviews5
bash -e kwidgetaddons5
bash -e kwindowsystem5
bash -e solid5
bash -e sonnet5
bash -e kauth5
bash -e kcompletion5
bash -e kcrash5
bash -e kconfigwidgets5
bash -e kservice5
bash -e kglobalaccel5
bash -e kpackage5
bash -e kiconthemes5
bash -e kjobwidgets5
bash -e knotifications5
bash -e ktextwidgets5
bash -e kxmlgui5
bash -e kbookmarks5
bash -e kwallet5
bash -e kded5
bash -e kio5
bash -e kirigami2
bash -e syndication5
bash -e knewstuff5
bash -e frameworkintegration5
bash -e kwayland5

