#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

set -e
PKG_VER=1.56.0
MAJOR=$(echo $PKG_VER | sed 's|.[^.]*$||g')
URL=https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/releases/$PKG_VER/downloads/NetworkManager-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-network-manager

# Get Package

cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

mkdir build
cd build


export CFLAGS+="-m32" 
export CXXFLAGS+="-m32"
export PKG_CONFIG="i686-pc-linux-gnu-pkg-config"

meson setup --prefix=/usr              \
    --libdir=/usr/lib32 \
    -Dcrypto=gnutls \
    -Ddbus_conf_dir=/usr/share/dbus-1/system.d \
    -Dlibaudit=no \
    -Dsession_tracking_consolekit=false \
    -Dsuspend_resume=systemd \
    -Dmodify_system=true \
    -Dselinux=false \
    -Dbluez5_dun=false \
    -Dlibpsl=false \
    -Dconcheck=false \
    -Debpf=false \
    -Diwd=false \
    -Dmodem_manager=false \
    -Dnm_cloud_setup=false \
    -Dnmcli=false \
    -Dnmtui=false \
    -Dovs=false \
    -Dppp=false \
    -Dteamdctl=false \
    -Dconfig_plugins_default=keyfile \
    -Difcfg_rh=false \
    -Difupdown=false \
    -Dnetconfig=no \
    -Dconfig_dns_rc_manager_default=symlink \
    -Dvapi=false \
    -Ddocs=false \
    -Dintrospection=false \
    -Dtests=no \
    -Dmore_asserts=no \
    -Dmore_logging=false \
    -Dqt=false \
      ..
ninja






# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
DESTDIR=$PWD/DESTDIR ninja install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /
cd /pkgs



sudo echo "network-manager lib32-libndp lib32-zlib lib32-systemd " > /pkgs/$PACKAGE/depends
sudo echo "lib32-polkit" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


