#!/bin/bash

export CFLAGS="-O2 "
export CXXFLAGS="-O2 "

PKG_VER=0.26.2
 
URL=https://github.com/p11-glue/p11-kit/releases/download/$PKG_VER/p11-kit-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=lib32-$(echo $DIR | sed 's|-[^-]*$||g')

# Get Package
export CC="gcc -m32"
export CXX="g++ -m32"
export PKG_CONFIG_PATH="i686-pc-linux-gnu-pkg-config"
cd /blfs/builds
wget $URL
tar -xvf $TAR
cd $DIR

# Build

sed '20,$ d' -i trust/trust-extract-compat &&
cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Update trust stores
/usr/sbin/make-ca -r
EOF

mkdir p11-build
cd p11-build

meson setup --prefix=/usr       \
      --buildtype=release \
      -Dtrust_paths=/etc/pki/anchors \
      --libdir=/usr/lib32

ninja


# Install
mkdir -p /pkgs/$PACKAGE/usr/lib32
DESTDIR=$PWD/DESTDIR ninja install
cp -Rv DESTDIR/usr/lib32/* /pkgs/$PACKAGE/usr/lib32
rm -rf DESTDIR
cp -rpv /pkgs/$PACKAGE/* /


cd /pkgs



sudo echo "p11-kit" > /pkgs/$PACKAGE/depends
sudo echo "coreutils systemd meson libffi libtasn1" > /pkgs/$PACKAGE/make-depends
sudo echo "$PKG_VER" > /pkgs/$PACKAGE/version
sudo tar -cvapf $PACKAGE.tar.xz $PACKAGE
sudo cp $PACKAGE.tar.xz /finished


cd /blfs/builds
sudo rm -r $DIR


