#!/bin/bash

export CFLAGS=-"O2"
export CXXFLAGS="-O2"


PATH=/opt/tucana/usr/bin:$PATH
PKG_VER=2.41
URL=https://ftp.gnu.org/gnu/glibc/glibc-$PKG_VER.tar.xz
TAR=$(echo $URL | sed -r 's|(.*)/||')
DIR=$(echo $TAR | sed 's|.tar.*||g')
PACKAGE=$(echo $DIR | sed 's|-[^-]*$||g')
FINISHED=/pkgs/$PACKAGE
set -e
# Get Package

cd /blfs/builds
wget $URL
wget https://www.linuxfromscratch.org/patches/lfs/development/glibc-$PKG_VER-fhs-1.patch
tar -xvf $TAR
cd $DIR

# Build
patch -Np1 -i ../glibc-$PKG_VER-fhs-1.patch
mkdir -v build
cd       build
echo "rootsbindir=/usr/sbin" > configparms
../configure                             \
      --prefix=/usr                      \
      --build=$(../scripts/config.guess) \
      --enable-kernel=4.14                \
      --with-headers=/usr/include    \
      --enable-multi-arch                \
      --disable-nscd \
      --host=x86_64-pc-linux-gnu libc_cv_slibdir=/usr/lib


make -j22


# Install
sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile
sudo PATH=/opt/tucana/usr/bin:$PATH make DESTDIR=/pkgs/glibc-temp install


sed '/RTLDLIST=/s@/usr@@g' -i /usr/bin/ldd

cd /blfs/builds
sudo rm -r $DIR

echo "COPY /pkgs/glibc-temp to root outside of the CHROOT!!!"
